### ISSUE TITLE
[BUG] Not able to finish katacoda Streetlight tutorial

### ISSUE THREAD

**Issue by pellea** [asyncapi/asyncapi#416]
**Describe the bug**
Not able to finish [katacoda Streetlight tutorial](https://www.katacoda.com/asyncapi/scenarios/streetlight-tut) due to some nodejs error.

**To Reproduce**
1. Start the tutorial
2. Try to run the command `ag asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto`
3. See error

**Error stacktrace**
```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module './build/Release/re2'
Require stack:
- /usr/lib/node_modules/@asyncapi/generator/node_modules/re2/re2.js
- /usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js
- /usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/customValidators.js
- /usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js
- /usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/index.js
- /usr/lib/node_modules/@asyncapi/generator/lib/generator.js
- /usr/lib/node_modules/@asyncapi/generator/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/lib/node_modules/@asyncapi/generator/node_modules/re2/re2.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/@asyncapi/generator/node_modules/re2/re2.js',
    '/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/utils.js',
    '/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/customValidators.js',
    '/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/parser.js',
    '/usr/lib/node_modules/@asyncapi/generator/node_modules/@asyncapi/parser/lib/index.js',
    '/usr/lib/node_modules/@asyncapi/generator/lib/generator.js',
    '/usr/lib/node_modules/@asyncapi/generator/cli.js'
  ]
}
```

**Comment by derberg** [comment]
@pellea thanks a lot for reporting it, we got signal from others about it and have an idea how to fix it. Some details here https://github.com/derberg/asyncapi-interactive-docs/issues/1
