### ISSUE TITLE
usage of schema vs payload

### ISSUE THREAD

**Issue by WAvdBeek** [asyncapi/asyncapi#427]
Can I get a clarification on the usage of schema vs payload

Just looking at the example about security of the tutorial:
https://www.asyncapi.com/docs/getting-started/security/
This example has a payload object hello-message, which contains the schema definition of the json payload
but it also references the schema snippet send-at.
what is the preferred usage of schemas vs payload?

Note that I have created a few AsyncAPI models without the keyword schema, and tried to generate code.
before commencing code generation I have validate the input with spectral lint.

The python code  gives the following error:
$ ag ../sdfobject-airquality.async.json @asyncapi/python-paho-template -o py3
S
[sdfobject-airquality.async.zip](https://github.com/asyncapi/asyncapi/files/5064077/sdfobject-airquality.async.zip)

omething went wrong:
Template render error: (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\@asyncapi\python-paho-template\template\main.py) [Line 7, Column 48]
  Error: Unable to call `the return value of (asyncapi["components"])["schemas"]`, which is undefined or falsey
    at Object._prettifyError (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\lib.js:36:11)
    at C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:561:19
    at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), <anonymous>:291:3)
    at Template.render (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:550:10)
    at Environment.renderString (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\node_modules\nunjucks\src\environment.js:378:17)
    at Promise (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:612:21)
    at new Promise (<anonymous>)
    at Generator.renderString (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:611:12)
    at Generator.renderFile (C:\Users\wovander\AppData\Roaming\npm\node_modules\@asyncapi\generator\lib\generator.js:635:17)
    at <anonymous>

if I run another template like  @asyncapi/html-template or  @asyncapi/nodejs-template 
it works fine.

attached the zipped used input file.

**Comment by jonaslagoni** [comment]
> what is the preferred usage of schemas vs payload?

@WAvdBeek depends on your preference I guess. `schemas` are great to have all the schemas in one place easy to locate and reference. Seems like you encountered a problem with the template itself not being able to handle something. Can you add your document in a comment instead of a zip file please 😄 ?

**Comment by derberg** [comment]
My guess is that the question is motivated by the fact that Python template, like the Java Spring Cloud Stream template, does not support schemas in a payload on a channel level. I saw @damaru-inc following in Java template approach to only grab schemas from `components.schemas` so this is why I guess the same was done in Python. 

@WAvdBeek try moving `payload` schemas to `components.schemas` and use `$ref` in `payload` to refer the schema from components. And if by doing this it will work, also report an issue in python template to improve this part

**Comment by derberg** [comment]
Hey @WAvdBeek 
I'll close this one as you already reported it here https://github.com/asyncapi/python-paho-template/issues/19
Feel free to reopen in case you have more questions, or just open a new issue
