### ISSUE TITLE
[BUG] ag codegeneration for python is not working

### ISSUE THREAD

**Issue by WAvdBeek** [asyncapi/asyncapi#431]
**Describe the bug**
code generation fails on  @asyncapi/python-paho-template
but works with 
@asyncapi/html-template
@asyncapi/nodejs-template

**To Reproduce**
1. Create a document 
```
{
   "asyncapi":"2.0.0",
   "info":{
      "title":"Air Quality",
      "version":"2019-06-13",
      "license":{
         "name":"one Data Model License",
         "url":"https://github.com/one-data-model/oneDM/blob/master/LICENSE",
         "x-copyright":"copyright 2016-2017, 2019 Open Connectivity Foundation, Inc. All rights reserved."
      },
      "termsOfService":"https://github.com/one-data-model/oneDM/blob/master/LICENSE",
      "description":" Generated from SDF Air Quality ",
      "contact":{
         "name":"API Support",
         "url":"http://www.example.com/support",
         "email":"support@example.com"
      }
   },
   "tags":[
      {
         "name":"SDF"
      },
      {
         "name":"Generated"
      }
   ],
   "servers":{
      "mosquitto":{
         "url":"mqtt://test.mosquitto.org",
         "protocol":"mqtt"
      }
   },
   "channels":{
      "Airquality":{
         "publish":{
            "operationId":"publish-airquality",
            "description":"This Resource describes a qualitative or measured contaminant that can be used to infer Air Quality. The Property 'valueType' indicates a qualitative or measured reading within the contaminantvalue Property. The Property 'contaminantvalue' can contain the actual sensed value with units per contaminant type. Qualitative is a representative value within the range provided where the minimum value is minimum contamination and maximum value is maximum contamination for the specific contaminant. The Property 'contaminantvalue' contains the actual measured or qualitative level. The Property 'range' contains the allowed range for the value that is being reported. If valueType is 'Measured' then the units for the contaminant types are as follows: Methanol (also known as Formaldehyde): CH2O (ug/m^3), Carbon Dioxide: CO2 (ppm), Carbon Monoxide: CO (ppm), Particulate Matter (less than 1 micron in diameter): PM1 (ug/m^3), Particulate Matter (less than 2. 5 microns in diameter): PM2. 5 (ug/m^3), Particulate Matter (less than 10 microns in diameter): PM10 (ug/m^3), Volatile Organic Compounds: VOC (ug/m^3).",
            "message":{
               "payload":{
                  "$ref":"#/components/schemas/airquality"
               }
            }
         }
      }
   },
   "components":{
      "schemas":{
         "airquality":{
            "type":"object",
            "properties":{
               "contaminanttype":{
                  "description":"The contaminant being measured.",
                  "enum":[
                     "CH2O",
                     "CO2",
                     "CO",
                     "PM1",
                     "PM2.5",
                     "PM10",
                     "VOC",
                     "Smoke",
                     "Odor",
                     "AirPollution"
                  ],
                  "type":"string",
                  "readOnly":true
               },
               "valuetype":{
                  "description":"The property that indicates whether the provided value is qualitative or measured.",
                  "enum":[
                     "Qualitative",
                     "Measured"
                  ],
                  "type":"string",
                  "readOnly":true
               },
               "contaminantvalue":{
                  "description":"The measured or qualitative value for the contaminant.",
                  "type":"integer",
                  "readOnly":true
               },
               "range":{
                  "description":"The valid range for the Property in the Resource as an integer. The first value in the array is the minimum value, the second value in the array is the maximum value.",
                  "items":{
                     "type":"integer"
                  },
                  "maxItems":2,
                  "minItems":2,
                  "type":"array",
                  "readOnly":true
               }
            }
         }
      }
   }
}
```
2. Try to run
ag ./sdfobject-airqualitypublisher.ascyncapi.json @asyncapi/python-paho-template -o <tempdir>

3. Try to validate the document doing '....'

Something went wrong:
Template render error: (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules@asyncapi\python-paho-template\template$$schema$$.py)
TypeError: typeMap.get is not a function
at Object._prettifyError (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\lib.js:36:11)
at C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:561:19
at eval (eval at _compile (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), :11:11)
at C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:611:9
at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), :361:3)
at Template.getExported (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:609:10)
at eval (eval at _compile (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), :10:5)
at createTemplate (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:313:9)
at handle (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:325:11)
at C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:337:9
at next (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\lib.js:326:7)
at Object.asyncIter (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\lib.js:332:3)
at Environment.getTemplate (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:319:9)
at Template.root [as rootRenderFunc] (eval at _compile (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:631:18), :8:5)
at Template.render (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:550:10)
at Environment.renderString (C:\Users\wovander\AppData\Roaming\npm\node_modules@asyncapi\generator\node_modules\nunjucks\src\environment.js:378:17)

**Expected behavior**
should create python code.

**Sample document**

[sdfobject-airqualitypublisher.ascyncapi.json.txt](https://github.com/asyncapi/asyncapi/files/5109928/sdfobject-airqualitypublisher.ascyncapi.json.txt)

note, changed the extension to .txt so that the file can be uploaded.

**Screenshots**

**Additional context**

**Comment by derberg** [comment]
Issue moved to [asyncapi/python-paho-template #19](https://github.com/asyncapi/python-paho-template/issues/19) via [**ZenHub**](https://www.zenhub.com/)
